language: python
python:
    - "2.6"
    - "2.7"
# command to install dependencies
notifications:
    email:
        recipients:
            - jpflorido@bioinfomgp.org
        on_success: always
install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install radon
    - pip install pep8
    - pip install mockito
# command to run tests
script:
    - py.test --doctest-modules --cov . --cov-report term-missing
after_success:
    - radon cc .
    - radon raw .
    - radon mi .
    - pep8 --statistics .
    - coveralls